// import { createElement } from 'lwc';
// import HelloWebComponent from 'c/helloWebComponent';

// describe('c-hello-web-component', () => {
//     afterEach(() => {
//         // The jsdom instance is shared across test cases in a single file so reset the DOM
//         while (document.body.firstChild) {
//             document.body.removeChild(document.body.firstChild);
//         }
//     });

//     it('TODO: test case generated by CLI command, please fill in test logic', () => {
//         // Arrange
//         const element = createElement('c-hello-web-component', {
//             is: HelloWebComponent
//         });

//         // Act
//         document.body.appendChild(element);

//         // Assert
//         // const div = element.shadowRoot.querySelector('div');
//         expect(1).toBe(1);
//     });
// });

import { createElement } from "lwc";
import MyComponent from "../helloWebComponent";

describe("<c-hello-web-component> test suite", () => {
  test("displays the correct greeting", () => {
    const element = createElement("c-hello-web-component", {
      is: MyComponent,
    });
    //   element.greeting = "World";
    document.body.appendChild(element);

    const greetingElement = element.shadowRoot.querySelector("div");
    expect(greetingElement.textContent).toBe("hello, Trailblazer!");
  });
});
